### ISSUE TITLE
Add option and flags to OCM CLI: `uninstall`, `--silent`, `-o YAML`

### ISSUE THREAD

**Issue by robertwol** [open-component-model/ocm-project#37]
**What would you like to be added**:
`ocm controller uninstall`

**Why is this needed**:
Currently, we can install OCM controllers on a cluster with `ocm controller install ...`

however, to cleanup, uninstall is not available as a `ocm` command

Ideally, we could implement uninstall command or we could exted exisitng install command to with `-d` to only produce the manifest which then it could be piped to `kubectl delete -f -`

decoration to be skipped
```
► installing ocm-controller with version latest
► got latest version "v0.10.0"
✔ successfully fetched install file
```

this will allow to uninstall components e.g. `ocm controller install -d | kubectl delete -f -`

**Comment by Skarlso** [comment]
Basically how this can work without keeping track of everything individually like service accounts, roles, rbac, etc, is by doing a reverse install using the same yaml that was used for installing. Meaning, the user will have to use the same version.

We just use delete with the same install yaml. The only stragglers are the issuers that we create and the certificates. Those we can delete by hand because we know we created them ( but don't fail if they don't exist ).

**Comment by hilmarf** [comment]
@Skarlso are the flags: `--silent` and `-o yaml` also supported? I haven't noticed them in the PR... Do we need to keep this ticket open?

**Comment by Skarlso** [comment]
Yep, we can leave this one open. I didn't want to mix things together.
