### ISSUE TITLE
Support dockerconfig in mpas-release-bootstrap

### ISSUE THREAD

**Issue by souleb** [open-component-model/ocm-project#55]
the bootstrap code expect a github token in order to transfer the component to `ghcr`. We should add the possibility to retrieve credentials from a dockerconfig.

**Comment by Skarlso** [comment]
The idea here was to not request a token via command line arguments but parse a user's existing`.dockerconfig` file and try accessing things from there. Since their environment should already be able to reach that.

It's a convenience feature really. :) Makes the thing more user-friendly, but also, the usage of temporary refresh/access tokens that the dockerconfig gives.
